title:              Christofer's Blog
email:              christofer_bustad@hotmail.com
description:        Some Personal Projects and a Few Random Thoughts
author:             Christofer Bustad
baseurl:            "/test-startbootstrap-clean-blog-jekyll"
url:                "https://bustad.github.io"

# Social Profiles
twitter_username:   
github_username:    
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
